# Generated by Django 4.0.5 on 2023-02-17 12:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FreeBikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_bike', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('time_stamp', models.DateTimeField()),
            ],
            managers=[
                ('free_bikes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exist', models.BooleanField()),
                ('post_code', models.IntegerField()),
                ('renting', models.IntegerField()),
                ('returning', models.IntegerField()),
                ('slots', models.IntegerField()),
                ('uid', models.IntegerField()),
            ],
            managers=[
                ('payment_terminal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
                ('altitude', models.FloatField()),
                ('ebikes', models.IntegerField()),
                ('has_ebikes', models.BooleanField()),
                ('normal_bikes', models.IntegerField()),
                ('last_updated', models.IntegerField()),
                ('payment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), size=None)),
                ('free_bikes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chr_models.freebikes')),
                ('payment_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chr_models.paymentterminal')),
            ],
            managers=[
                ('stations', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=6)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chr_models.stations')),
            ],
            managers=[
                ('company', django.db.models.manager.Manager()),
            ],
        ),
    ]
