# Generated by Django 4.0.5 on 2023-02-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chr_models', '0003_alter_freebikes_id_bike_alter_freebikes_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stations',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
