# Generated by Django 4.0.5 on 2023-02-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chr_models', '0004_alter_company_name_alter_stations_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stations',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
