# Generated by Django 4.0.5 on 2023-02-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chr_models', '0006_alter_stations_has_ebikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='ebikes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
