# Generated by Django 4.0.5 on 2023-02-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chr_models', '0007_alter_stations_ebikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stations',
            name='ebikes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stations',
            name='has_ebikes',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
