# Generated by Django 4.0.5 on 2023-02-18 02:12

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chr_models', '0010_alter_stations_post_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.URLField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('typology', models.CharField(blank=True, max_length=100, null=True)),
                ('titular', models.CharField(blank=True, max_length=100, null=True)),
                ('inversion', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('map', models.CharField(blank=True, default='sin informacion', max_length=100, null=True)),
            ],
            managers=[
                ('table', django.db.models.manager.Manager()),
            ],
        ),
    ]
