# Generated by Django 4.0.5 on 2023-02-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chr_models', '0011_tabledata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
