# Generated by Django 4.0.5 on 2023-02-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chr_models', '0014_alter_tabledata_date_alter_tabledata_inversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='name',
            field=models.URLField(blank=True, null=True),
        ),
    ]
